#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pollaris"
name = "Pollaris"
description.en = "Polling tool to plan, organise and make decisions quickly"
description.fr = "Outil de sondage pour planifier, organiser et prendre rapidement des décisions"

version = "1.2.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0-only"
website = "https://pollaris.org/"
admindoc = "https://framagit.org/pollaris/pollaris/-/blob/main/docs/administrators/install.md"
code = "https://framagit.org/pollaris/pollaris/"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://framagit.org/pollaris/pollaris/-/archive/1.2.1/pollaris-1.2.1.tar.bz2"
    sha256 = "49ca9a635ce4a135596838cdb7958075d7687a16a8e52e37f20258ab819edbc5"

    autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]

    packages = "postgresql, php8.4-ctype, php8.4-iconv, php8.4-intl, php8.4-pdo, php8.4-pgsql, php8.4-zip, php8.4-xml"

    [resources.database]
    type = "postgresql"

    [resources.composer]
    version = "2.9.5"
    
